In [1]:
# import plotly.graph_objects as go
# import networkx as nx
import sys
import importlib
import os
# import plotly.offline as py

import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
import pickle as pk
from datetime import datetime
from datetime import timedelta
from datetime import time
import pandas as pd
import numpy as np

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))


In [4]:
#!/ usr/bin/env python3 .7
# Copyright 2020 , Gurobi Optimization , LLC
# This example formulates and solves the following simple QP model :
# minimize
# x^2 + x*y + y^2 + y*z + z^2 + 2 x
# subject to
# x + 2 y + 3 z >= 4
# x + y >= 1
# x, y, z non - negative
#
# It solves it once as a continuous model , and once as an integer model .
import gurobipy as gp
from gurobipy import GRB
# Create a new model
m = gp.Model("qp")
# Create variables
x = m.addVar( ub =1.0 , name ="x")
y = m.addVar( ub =1.0 , name ="y")
z = m.addVar( ub =1.0 , name ="z")
# Set objective : x^2 + x*y + y^2 + y*z + z^2 + 2 x
obj = x * x + x * y + y * y + y * z + z * z + 2* x
m.setObjective( obj )
# Add constraint : x + 2 y + 3 z <= 4
m.addConstr ( x + 2 * y + 3 * z >= 4 , "c0")
# Add constraint : x + y >= 1
m.addConstr ( x + y >= 1 , "c1")
m.optimize ()
for v in m.getVars():
    print('%s %g'%(v.varName, v.x ))
    print('Obj: %g' % obj.getValue())
x.vType = GRB.INTEGER
y.vType = GRB.INTEGER
z.vType = GRB.INTEGER
m.optimize()
for v in m.getVars ():
    print('%s %g'%(v.varName , v.x ))

print('Obj: %g'%obj.getValue())

Academic license - for non-commercial use only - expires 2023-08-21
Using license file /Users/ravitpichayavet/gurobi.lic
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 2 rows, 3 columns and 5 nonzeros
Model fingerprint: 0xc501370b
Model has 5 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [2e+00, 2e+00]
  QObjective range [2e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 4e+00]
Presolve time: 0.02s
Presolved: 2 rows, 3 columns, 5 nonzeros
Presolved model has 5 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 2
 AA' NZ     : 6.000e+00
 Factor NZ  : 1.000e+01
 Factor Ops : 3.000e+01 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   1.6901

In [210]:
# Create a new model
m = gp.Model("qp")
# Create variables
x1 = m.addVar(name ="x1", lb = -GRB.INFINITY)
x2 = m.addVar(name ="x2",lb = -GRB.INFINITY)
x3 = m.addVar(name ="x3",lb = -GRB.INFINITY)
x4 = m.addVar(name ="x4",lb = -GRB.INFINITY)
# Set objective : x^2 + x*y + y^2 + y*z + z^2 + 2 x
obj = 3*(x1 * x1) + 3*(x2 * x2) + 4*(x3 * x3) + 5*(x4 * x4) + 3*(x1 * x2) + 5*(x1 * x3) + (x2 * x4) - (11*x1)- (5*x4)
m.setObjective(obj ,GRB.MINIMIZE)
# Add constraint: 
m.addConstr ( (3*x1) - (3*x2) - (2*x3) + x4 == 0 , "c0")
m.addConstr ( (4*x1) + x2 - x3 - (2*x4) == 0 , "c1")
m.addConstr ( -x1 + x2 <= -1 , "c2")
m.addConstr ( (3*x1) + x3 <= 4 , "c3")
m.addConstr ( (3*x1) + x3 >= -2 , "c4")

m.update()
# x1.vType = GRB.INTEGER
# x2.vType = GRB.INTEGER
# x3.vType = GRB.INTEGER
# x4.vType = GRB.INTEGER
m.optimize()

for v in m.getVars():
    print('%s %g'%(v.varName, v.x ))
print('Obj: %g' % obj.getValue())

Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (mac64)
Thread count: 8 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 5 rows, 4 columns and 14 nonzeros
Model fingerprint: 0x911cdcf5
Model has 7 quadratic objective terms
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [5e+00, 1e+01]
  QObjective range [2e+00, 1e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+00]
Presolve removed 1 rows and 0 columns
Presolve time: 0.02s
Presolved: 4 rows, 5 columns, 13 nonzeros
Presolved model has 7 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 7
 AA' NZ     : 2.000e+01
 Factor NZ  : 2.800e+01
 Factor Ops : 1.400e+02 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -3.95944805e-09 -1.50000000e+03  1.00e+03 1.10e+01  1.00e+06     0s
   1   1.74003686e+0

In [73]:
m.getQ().toarray(),m.getA().toarray(),

(array([[3., 3., 5., 0.],
        [0., 3., 0., 1.],
        [0., 0., 4., 0.],
        [0., 0., 0., 5.]]),
 array([[ 3., -3., -2.,  1.],
        [ 4.,  1., -1., -2.],
        [-1.,  1.,  0.,  0.],
        [ 3.,  0.,  1.,  0.],
        [ 3.,  0.,  1.,  0.]]))

In [216]:
W = np.array([
    [6, 3, 5, 0],
    [3, 6, 0, 1],
    [5, 0, 8, 0],
    [0, 1, 0, 10] ])
A = np.array([
    [3, -3, -2, 1],
    [4, 1, -1, -2] ])
E = np.array([
    [-1, 1, 0, 0],
    [3, 0, 1, 0] ])
C = np.array([-11,0,0,-5])
b = np.array([0,0])
l = np.array([-np.inf,-2])
h = np.array([-1,4])

W_inv = np.linalg.inv(W)



In [217]:
epsilon = 1e-8
u0 = [10, -10]

left_t = np.matmul(W_inv,A.T)
mid_t = np.linalg.inv(np.matmul(A,left_t))
right_t = np.matmul(A,W_inv)

M = W_inv - np.matmul(np.matmul(left_t,mid_t),right_t)

s = np.matmul(W_inv, ((np.matmul(np.matmul(A.T, mid_t) ,(np.matmul(right_t,C)+b) )) - C))
print("M:",M)
print("s:",s)

M: [[ 0.01512507  0.00407213  0.02617801  0.01919721]
 [ 0.00407213  0.03955788 -0.03141361  0.04363002]
 [ 0.02617801 -0.03141361  0.08376963 -0.0052356 ]
 [ 0.01919721  0.04363002 -0.0052356   0.06282723]]
s: [0.26236184 0.26294357 0.2617801  0.52530541]


In [218]:
W_inv,np.matmul(np.matmul(left_t,mid_t),right_t),M

(array([[ 0.74097331, -0.37676609, -0.46310832,  0.03767661],
        [-0.37676609,  0.3610675 ,  0.23547881, -0.03610675],
        [-0.46310832,  0.23547881,  0.4144427 , -0.02354788],
        [ 0.03767661, -0.03610675, -0.02354788,  0.10361068]]),
 array([[ 0.72584824, -0.38083823, -0.48928633,  0.0184794 ],
        [-0.38083823,  0.32150962,  0.26689242, -0.07973677],
        [-0.48928633,  0.26689242,  0.33067307, -0.01831228],
        [ 0.0184794 , -0.07973677, -0.01831228,  0.04078345]]),
 array([[ 0.01512507,  0.00407213,  0.02617801,  0.01919721],
        [ 0.00407213,  0.03955788, -0.03141361,  0.04363002],
        [ 0.02617801, -0.03141361,  0.08376963, -0.0052356 ],
        [ 0.01919721,  0.04363002, -0.0052356 ,  0.06282723]]))

In [219]:
ITERATION = 10000
ME_T = np.matmul(M, E.T); EME_T = np.matmul(E,ME_T); 
n_EME_T = EME_T.shape[0]; I = np.identity(n_EME_T)
Es = np.matmul(E,s)
x = np.matmul(ME_T,u0) + s
u_prev = u0; x_prev = len(x)*np.inf; 

for i in range(ITERATION):
    x_out = np.matmul(ME_T,u_prev) + s
    Ex = np.matmul(E,x_out)
#     print("u:",u_prev)
#     print("x:",x_out)
#     print()
#     u_cur = u_prev+(-np.matmul(EME_T,u_prev) + g_func((np.matmul((EME_T-I),u_prev)+Es),l,h) - Es)*(1/epsilon)
    u_cur = (u_prev + (g_func(Ex-u_prev,l,h) - Ex))
    if (all(abs(x_out-x_prev))<epsilon):
        print("Gap less than tolerance:{}!".format(epsilon))
        print("No. of iterations:{}".format(i+1))
        print("u:",u_prev)
        print("x:",x_out)
        break
    x_prev = x_out
    u_prev = u_cur


Gap less than tolerance:1e-08!
No. of iterations:694
u: [-21.5   0. ]
x: [ 5.00000000e-01 -5.00000000e-01  1.50000000e+00 -1.36557432e-14]


In [220]:
print("u:",u_prev)
print("x:",x_out)
for v in m.getVars():
    print('%s %g'%(v.varName, v.x ))

u: [-21.5   0. ]
x: [ 5.00000000e-01 -5.00000000e-01  1.50000000e+00 -1.36557432e-14]
x1 0.5
x2 -0.5
x3 1.5
x4 -2.27213e-12


In [122]:
def g_func(z, l, h):
    g = []
    for i in range(len(z)):
        if ((l[i] == -np.inf) and (h[i]==np.inf)):
            g.append(z[i])
        elif (l[i] == -np.inf):
            if (z[i]<= h[i]): g.append(z[i])
            else: g.append(h[i])
        elif (h[i]==np.inf):
            if (z[i]>= l[i]): g.append(z[i])
            else: g.append(l[i])
        else:
            if (z[i]< l[i]): g.append(l[i])
            elif ((l[i]<=z[i])and(z[i]<=h[i])): g.append(z[i])
            else: g.append(h[i])
    return np.array(g)

array([-1., -2.])

In [119]:
np.identity()

array([[1., 0.],
       [0., 1.]])

In [174]:
g_func((np.matmul((EME_T-I),u_prev)+Es),l,h) 

array([-1., -2.])

In [173]:
(np.matmul((EME_T-I),u_prev)+Es)

array([ 8842335.48562877, -3845182.44802318])

In [176]:
Es,u_prev

(array([5.81733566e-04, 1.04886562e+00]),
 array([-9999990.        ,  7628262.25130888]))

In [175]:
EME_T

array([[ 0.04653869, -0.09075044],
       [-0.09075044,  0.37696335]])